# Generated by Django 4.0.4 on 2022-05-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CropStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('sunlight', models.IntegerField()),
            ],
        ),
    ]
