# Generated by Django 4.0.4 on 2022-05-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop_stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropstats',
            name='crop_health',
            field=models.CharField(blank=True, choices=[('good', 'Good'), ('same', 'Same'), ('worse', 'Worse')], max_length=5, null=True),
        ),
    ]
